// FIX: Replaced placeholder content with a complete i18n implementation.
// This provides all necessary translation strings for English and Spanish,
// resolving module loading errors across the application.
const en = {
  'language.self': 'English',
  // Common
  'common.confirm': 'Confirm',
  'common.cancel': 'Cancel',

  // Toasts
  'toast.checking_updates': 'Checking for updates...',
  'toast.latest_version': 'You are on the latest version!',
  'toast.generating_voice': 'Generating {voiceName} voice sample...',
  'toast.generate_voice_error': 'Could not generate voice sample.',
  'toast.play_voice_error': 'Failed to play voice sample.',
  'toast.profile_updated': 'Profile updated successfully!',
  'toast.clear_data_success': 'All mission and conversation data has been cleared.',
  'toast.connector_connected': '{connectorName} has been connected.',
  'toast.connector_disconnected': '{connectorName} has been disconnected.',

  // Sidebar
  'sidebar.subtitle': 'AI Configuration',
  'sidebar.section.main': 'Main',
  'sidebar.item.cognitive_profile': 'Cognitive Profile',
  'sidebar.section.settings': 'Settings',
  'sidebar.item.configuration': 'Configuration',
  'sidebar.section.workspace': 'Workspace',
  'sidebar.section.memoria_base': 'Base Memory',
  'sidebar.section.configuracion_operacion': 'Configuration & Operation',
  'sidebar.item.missions': 'Home',


  // Config Page
  'page_config.title': 'Configuration',
  'page_config.subtitle': 'Manage the core settings of your Agentic Brain.',
  'page_config.tab.general': 'General',
  'page_config.tab.personalization': 'Personalization',
  'page_config.tab.notifications': 'Notifications',
  'page_config.tab.connectors': 'Connectors',
  'page_config.tab.suite_integrator': 'Suite Integrator',
  'page_config.tab.data_controls': 'Data Controls',
  'page_config.tab.security': 'Security',

  // General Page
  'page_general.title': 'General',
  'page_general.subtitle': 'Define base experience: startup, appearance, and voice.',
  'page_general.system.title': 'System',
  'page_general.system.updates.title': 'Check for updates',
  'page_general.system.updates.desc': 'Ensure you have the latest features and security updates.',
  'page_general.system.updates.button': 'Check for updates',
  'page_general.system.updates.button_checking': 'Checking...',
  'page_general.system.updates.tooltip': 'Current version: 1.0.0',
  'page_general.system.login.title': 'Run on login',
  'page_general.system.login.desc': 'Automatically launch the agentic brain when you start your computer.',
  'page_general.system.shortcut.title': 'Assistant window shortcut',
  'page_general.system.shortcut.desc': 'The global keyboard shortcut to open the assistant.',
  'page_general.appearance.title': 'Appearance',
  'page_general.appearance.theme.title': 'Theme',
  'page_general.appearance.theme.desc': 'Choose a light or dark theme, or sync with your system.',
  'page_general.appearance.theme.placeholder': 'Select theme',
  'page_general.appearance.theme.system': 'System',
  'page_general.appearance.theme.light': 'Light',
  'page_general.appearance.theme.dark': 'Dark',
  'page_general.appearance.accent.title': 'Accent Color',
  'page_general.appearance.accent.desc': 'Select your preferred accent color for UI elements.',
  'page_general.appearance.textsize.title': 'Text Size',
  'page_general.appearance.textsize.desc': 'Adjust the text size for better readability.',
  'page_general.appearance.textsize.reset': 'Reset',
  'page_general.language.title': 'Language & Voice',
  'page_general.language.ui.title': 'Language',
  'page_general.language.ui.desc': 'The primary language for the UI.',
  'page_general.language.ui.placeholder': 'Select language',
  'page_general.language.spoken.title': 'Spoken Language',
  'page_general.language.spoken.desc': "The language the agent will speak in.",
  'page_general.language.spoken.auto': 'Automatic',
  'page_general.language.voice.title': 'Voice',
  'page_general.language.voice.desc': "Choose the agent's voice.",

  // Notifications Page
  'page_notifications.title': 'Notifications',
  'page_notifications.subtitle': 'Orchestrate channels and triggers by event type.',
  'page_notifications.rules.title': 'Notification Rules',
  'page_notifications.rules.replies.title': 'Replies',
  'page_notifications.rules.replies.desc': 'Notifications for direct replies and mentions.',
  'page_notifications.rules.tasks.title': 'Tasks',
  'page_notifications.rules.tasks.desc': 'Alerts for task assignments, updates, and deadlines.',
  'page_notifications.rules.tasks.manage': 'Manage tasks',
  'page_notifications.rules.projects.title': 'Projects',
  'page_notifications.rules.projects.desc': 'Receive email invitations for new projects.',
  'page_notifications.chip.notifications': 'Notifications',
  'page_notifications.chip.email': 'Email',

  // Personalization Page
  'page_personalization.title': 'Personalization',
  'page_personalization.subtitle': "Shape the agent's behavior for brand and persona consistency.",
  'page_personalization.enable.title': 'Enable Personalization',
  'page_personalization.enable.desc': "Turn on to customize the agent's personality and instructions.",
  'page_personalization.personality.title': 'Personality',
  'page_personalization.personality.desc': "Choose the agent's default tone.",
  'page_personalization.personality.default': 'Default',
  'page_personalization.personality.talkative': 'Talkative',
  'page_personalization.personality.forthright': 'Forthright',
  'page_personalization.personality.witty': 'Witty',
  'page_personalization.instructions.title': 'Custom Instructions',
  'page_personalization.instructions.desc': 'Provide a master prompt for the agent.',
  'page_personalization.about.title': 'About You',
  'page_personalization.about.nickname.title': 'Nickname',
  'page_personalization.about.nickname.desc': 'How the agent should refer to you.',
  'page_personalization.about.occupation.title': 'Occupation',
  'page_personalization.about.occupation.desc': 'Your professional role.',
  'page_personalization.about.occupation.placeholder': 'e.g., Strategy Director',
  'page_personalization.about.more.title': 'More about you',
  'page_personalization.about.more.desc': 'Add details about your interests and preferences.',
  'page_personalization.capabilities.title': 'Agent Capabilities',
  'page_personalization.capabilities.memory.title': 'Memory',
  'page_personalization.capabilities.memory.desc': 'Allow the agent to remember past conversations.',
  'page_personalization.capabilities.memory.manage': 'Manage',
  'page_personalization.capabilities.memory.reference': 'Reference saved memories',
  'page_personalization.capabilities.recording.title': 'Recording Mode',
  'page_personalization.capabilities.recording.desc': 'Access and review transcripts of your interactions.',
  'page_personalization.capabilities.search.title': 'Internet Search',
  'page_personalization.capabilities.search.desc': 'Enable the agent to search the internet for up-to-date information.',

  // Connectors Page
  'page_connectors.title': 'Connectors',
  'page_connectors.subtitle': 'Manage integrations with your work tools.',
  'page_connectors.integrations.title': 'Available Integrations',
  'page_connectors.tooltip.agent_mode': 'Allows autonomous actions with confirmation.',
  'page_connectors.status.connected': 'Connected',
  'page_connectors.status.not_connected': 'Not Connected',
  'page_connectors.button.manage': 'Manage',
  'page_connectors.button.connect': 'Connect',
  
  // Data Controls Page
  'page_datacontrols.title': 'Data Controls',
  'page_datacontrols.subtitle': 'Manage your data, privacy, and how information is used.',
  'page_datacontrols.training.title': 'Training & Privacy',
  'page_datacontrols.training.improve.title': 'Improve the model',
  'page_datacontrols.training.improve.desc': 'Allow your anonymized conversations to be used to train our models.',
  'page_datacontrols.mission.title': 'Mission & Conversation Data',
  'page_datacontrols.mission.clear.title': 'Clear all data',
  'page_datacontrols.mission.clear.desc': 'This will permanently delete all your mission progress and conversation history. This action cannot be undone.',
  'page_datacontrols.mission.clear.button': 'Clear Data',
  'page_datacontrols.dialog.clear.title': 'Are you absolutely sure?',
  'page_datacontrols.dialog.clear.desc': 'This will permanently delete all mission and conversation data. This action cannot be undone.',
  'page_datacontrols.dialog.clear.confirm': 'Yes, clear data',

  // Security Page
  'page_security.title': 'Security',
  'page_security.subtitle': "Manage your account's security settings.",
  'page_security.auth.title': 'Authentication',
  'page_security.auth.password.title': 'Password',
  'page_security.auth.password.desc': "It's a good idea to use a strong password that you're not using elsewhere.",
  'page_security.auth.password.button': 'Change password',
  'page_security.auth.2fa.title': 'Two-Factor Authentication (2FA)',
  'page_security.auth.2fa.desc': 'Add an extra layer of security to your account.',
  'page_security.sessions.title': 'Active Sessions',
  'page_security.sessions.current.title': 'Current Session',
  'page_security.sessions.current.desc': '{browser} on {os} - {location}',
  'page_security.sessions.current.status': 'Active now',
  'page_security.sessions.logout.button': 'Log out of all other sessions',

  // Agent Brain Specific
  'datacontrols.consents.title': 'Agent Data Consents',
  'datacontrols.consents.description': 'Grant specific permissions to agents to access your data. This ensures you have granular control over how your information is used. Changes are saved automatically.',
  'datacontrols.consents.agent.drwin': 'Dr. Win',
  'datacontrols.consents.agent.validateagent': 'ValidateAgent',
  'datacontrols.consents.agent.createagent': 'CreateAgent',
  'datacontrols.consents.resource.organization': 'Organization',
  'datacontrols.consents.resource.organization.desc': 'Legal information, size, industry, etc.',
  'datacontrols.consents.resource.projects': 'Projects',
  'datacontrols.consents.resource.projects.desc': 'Ideas, drafts, and created projects.',
  'datacontrols.consents.action.read': 'Read',
  'datacontrols.consents.action.search': 'Search',
  'datacontrols.consents.action.validate': 'Validate',
  'datacontrols.consents.action.create': 'Create',
  'org.legal_info': 'Legal Information',
  'org.legal_name': 'Legal Name',
  'org.legal_name.desc': 'The official registered name of the company.',
  'org.brand_name': 'Brand Name',
  'org.brand_name.desc': 'The name used for marketing, if different.',
  'org.vat': 'VAT ID',
  'org.vat.desc': 'The unique tax identification number.',
  'org.details': 'Organization Details',
  'org.country': 'Country',
  'org.country.desc': 'The primary country of operation.',
  'org.industry': 'Industry (NACE)',
  'org.industry.desc': 'The main sector of economic activity.',
  'org.size': 'Company Size',
  'org.size.desc': 'The number of employees in your organization.',
  'org.size.solo': 'Solo (1)',
  'org.size.micro': 'Micro (1-9)',
  'org.size.sme': 'SME (10-249)',
  'org.size.mid': 'Mid-Cap (250-1000)',
  'org.size.large': 'Large (1000+)',
  'org.preferences': 'Grant Preferences',
  'org.budget': 'Annual R&D Budget',
  'org.budget.desc': 'Approximate annual budget for R&D projects.',
  'org.languages': 'Supported Languages',
  'org.languages.desc': 'Languages for proposals (comma-separated).',
  'org.update_button': 'Update Profile',
  
  // Unified Cognitive Profile
  'cognitive_profile.title': 'Unified Cognitive Profile',
  'cognitive_profile.subtitle': 'This is the intelligent identity core of your organization, the living knowledge base for all agents.',
  'profile.title': 'Cognitive Profile',
  'profile.subtitle': 'This information will serve as the memory base for all agent operations.',
  'profile.initial_data': 'Initial Data & AI Extraction',
  'profile.initial_data.desc': 'Enter the website URL to start the automatic information extraction.',
  'profile.company_url': 'Website URL',
  'profile.ai_extraction_status': 'AI scanning website...',
  'profile.ai_suggestion': "I've detected that your company offers solar energy solutions in Europe. Shall I add the 'Renewable Energy' tag and set the target audience to 'Industrial companies'?",
  'profile.basic_info': 'Basic Information',
  'profile.description': 'Company Description',
  'profile.description.desc': 'A brief summary of your company\'s mission and activities.',
  'profile.sector': 'Primary Sector',
  'profile.location': 'Primary Location',
  'profile.products': 'Products / Services',
  'profile.products_audience': 'Products & Target Audience',
  'profile.target_audience': 'Target Audience',
  'profile.context_docs': 'Contextual Documents',
  'profile.context_docs.desc': 'Enrich the profile with documents (PDF, DOCX, etc.). The content will be extracted and made available to the agents.',
  'profile.upload_button': 'Upload File',
  'profile.doc_table.name': 'Name',
  'profile.doc_table.summary': 'AI Summary',
  'profile.doc_table.tags': 'Tags',
  'profile.update_button': 'Update Profile',

  // Suite Integrator
  'suite_integrator.title': 'Suite Integrator',
  'suite_integrator.subtitle': 'The cognitive bus connecting profiles, agents, and modules via contracts, events, and semantic memory.',
  'suite_integrator.contracts.title': 'Data Contracts (JSON Schemas)',
  'suite_integrator.contracts.desc': 'Versioned schemas ensuring data consistency across the ecosystem.',
  'suite_integrator.events.title': 'Live Event Log',
  'suite_integrator.events.desc': 'Real-time stream of events published by the integrator to sync modules.',
  'suite_integrator.events.table.event': 'Event',
  'suite_integrator.events.table.source': 'Source',
  'suite_integrator.events.table.profile': 'Profile ID',
  'suite_integrator.events.table.correlation': 'Correlation ID',
  'suite_integrator.semantic_search.title': 'Semantic Search (Vector Memory)',
  'suite_integrator.semantic_search.desc': 'Query the cognitive profiles using natural language.',
  'suite_integrator.semantic_search.placeholder': 'e.g., renewable energy companies in Spain with TRL > 5',
  'suite_integrator.semantic_search.button': 'Search',
  'suite_integrator.semantic_search.searching': 'Searching...',
  'suite_integrator.semantic_search.interpretation': 'Semantic Interpretation',
  'suite_integrator.semantic_search.no_results': 'No matching profiles found.',

  // Missions Page (Chat)
  'missions.chat.welcome': 'How can I help you?',
  'missions.chat.placeholder': 'Ask anything you want',
  'missions.chat.thinking': 'Dr. Win is thinking...',
  'missions.suggestions.title': 'Not sure where to start? Try one of these:',
  'missions.suggestions.s1.title': 'Want me to analyze funding opportunities?',
  'missions.suggestions.s1.desc': 'I can review active calls and tell you which ones best fit your company or project.',
  'missions.suggestions.s2.title': 'Want me to guide you step-by-step in the application?',
  'missions.suggestions.s2.desc': 'I can accompany you in each phase: search, preparation, writing, and submission of the proposal.',
  'missions.suggestions.s3.title': 'Want me to remind you of important deadlines?',
  'missions.suggestions.s3.desc': 'I can send you alerts before calls close or pending deliverables are due.',
};

const es = {
  'language.self': 'Español',
  // Common
  'common.confirm': 'Confirmar',
  'common.cancel': 'Cancelar',

  // Toasts
  'toast.checking_updates': 'Buscando actualizaciones...',
  'toast.latest_version': '¡Estás en la última versión!',
  'toast.generating_voice': 'Generando muestra de voz {voiceName}...',
  'toast.generate_voice_error': 'No se pudo generar la muestra de voz.',
  'toast.play_voice_error': 'Error al reproducir la muestra de voz.',
  'toast.profile_updated': '¡Perfil actualizado correctamente!',
  'toast.clear_data_success': 'Todos los datos de misiones y conversaciones han sido eliminados.',
  'toast.connector_connected': '{connectorName} ha sido conectado.',
  'toast.connector_disconnected': '{connectorName} ha sido desconectado.',

  // Sidebar
  'sidebar.subtitle': 'Configuración IA',
  'sidebar.section.main': 'Principal',
  'sidebar.item.cognitive_profile': 'Perfil Cognitivo',
  'sidebar.section.settings': 'Ajustes',
  'sidebar.item.configuration': 'Configuración',
  'sidebar.section.workspace': 'Espacio de Trabajo',
  'sidebar.section.memoria_base': 'Memoria Base',
  'sidebar.section.configuracion_operacion': 'Configuración y Operación',
  'sidebar.item.missions': 'Inicio',
  
  // Config Page
  'page_config.title': 'Configuración',
  'page_config.subtitle': 'Gestiona los ajustes principales de tu Agentic Brain.',
  'page_config.tab.general': 'General',
  'page_config.tab.personalization': 'Personalización',
  'page_config.tab.notifications': 'Notificaciones',
  'page_config.tab.connectors': 'Conectores',
  'page_config.tab.suite_integrator': 'Integrador de la Suite',
  'page_config.tab.data_controls': 'Control de Datos',
  'page_config.tab.security': 'Seguridad',

  // General Page
  'page_general.title': 'General',
  'page_general.subtitle': 'Define la experiencia base: inicio, apariencia y voz.',
  'page_general.system.title': 'Sistema',
  'page_general.system.updates.title': 'Buscar actualizaciones',
  'page_general.system.updates.desc': 'Asegúrate de tener las últimas funciones y actualizaciones de seguridad.',
  'page_general.system.updates.button': 'Buscar actualizaciones',
  'page_general.system.updates.button_checking': 'Buscando...',
  'page_general.system.updates.tooltip': 'Versión actual: 1.0.0',
  'page_general.system.login.title': 'Ejecutar al iniciar sesión',
  'page_general.system.login.desc': 'Lanza automáticamente el cerebro agéntico cuando inicias tu ordenador.',
  'page_general.system.shortcut.title': 'Atajo de ventana del asistente',
  'page_general.system.shortcut.desc': 'El atajo de teclado global para abrir el asistente.',
  'page_general.appearance.title': 'Apariencia',
  'page_general.appearance.theme.title': 'Tema',
  'page_general.appearance.theme.desc': 'Elige un tema claro, oscuro o sincronízalo con tu sistema.',
  'page_general.appearance.theme.placeholder': 'Seleccionar tema',
  'page_general.appearance.theme.system': 'Sistema',
  'page_general.appearance.theme.light': 'Claro',
  'page_general.appearance.theme.dark': 'Oscuro',
  'page_general.appearance.accent.title': 'Color de acento',
  'page_general.appearance.accent.desc': 'Selecciona tu color de acento preferido para los elementos de la interfaz.',
  'page_general.appearance.textsize.title': 'Tamaño del texto',
  'page_general.appearance.textsize.desc': 'Ajusta el tamaño del texto para una mejor legibilidad.',
  'page_general.appearance.textsize.reset': 'Reiniciar',
  'page_general.language.title': 'Idioma y Voz',
  'page_general.language.ui.title': 'Idioma',
  'page_general.language.ui.desc': 'El idioma principal de la interfaz de usuario.',
  'page_general.language.ui.placeholder': 'Seleccionar idioma',
  'page_general.language.spoken.title': 'Idioma hablado',
  'page_general.language.spoken.desc': 'El idioma en el que hablará el agente.',
  'page_general.language.spoken.auto': 'Automático',
  'page_general.language.voice.title': 'Voz',
  'page_general.language.voice.desc': 'Elige la voz del agente.',

  // Notifications Page
  'page_notifications.title': 'Notificaciones',
  'page_notifications.subtitle': 'Orquesta canales y disparadores por tipo de evento.',
  'page_notifications.rules.title': 'Reglas de Notificación',
  'page_notifications.rules.replies.title': 'Respuestas',
  'page_notifications.rules.replies.desc': 'Notificaciones para respuestas directas y menciones.',
  'page_notifications.rules.tasks.title': 'Tareas',
  'page_notifications.rules.tasks.desc': 'Alertas para asignaciones de tareas, actualizaciones y plazos.',
  'page_notifications.rules.tasks.manage': 'Gestionar tareas',
  'page_notifications.rules.projects.title': 'Proyectos',
  'page_notifications.rules.projects.desc': 'Recibe invitaciones por correo para nuevos proyectos.',
  'page_notifications.chip.notifications': 'Notificaciones',
  'page_notifications.chip.email': 'Email',

  // Personalization Page
  'page_personalization.title': 'Personalización',
  'page_personalization.subtitle': 'Modela el comportamiento del agente para la consistencia de marca y persona.',
  'page_personalization.enable.title': 'Activar Personalización',
  'page_personalization.enable.desc': 'Activa para personalizar la personalidad e instrucciones del agente.',
  'page_personalization.personality.title': 'Personalidad',
  'page_personalization.personality.desc': 'Elige el tono predeterminado del agente.',
  'page_personalization.personality.default': 'Predeterminado',
  'page_personalization.personality.talkative': 'Hablador',
  'page_personalization.personality.forthright': 'Directo',
  'page_personalization.personality.witty': 'Ingenioso',
  'page_personalization.instructions.title': 'Instrucciones Personalizadas',
  'page_personalization.instructions.desc': 'Proporciona un prompt maestro para el agente.',
  'page_personalization.about.title': 'Sobre Ti',
  'page_personalization.about.nickname.title': 'Apodo',
  'page_personalization.about.nickname.desc': 'Cómo debería referirse a ti el agente.',
  'page_personalization.about.occupation.title': 'Ocupación',
  'page_personalization.about.occupation.desc': 'Tu rol profesional.',
  'page_personalization.about.occupation.placeholder': 'ej: Director de Estrategia',
  'page_personalization.about.more.title': 'Más sobre ti',
  'page_personalization.about.more.desc': 'Añade detalles sobre tus intereses y preferencias.',
  'page_personalization.capabilities.title': 'Capacidades del Agente',
  'page_personalization.capabilities.memory.title': 'Memoria',
  'page_personalization.capabilities.memory.desc': 'Permite al agente recordar conversaciones pasadas.',
  'page_personalization.capabilities.memory.manage': 'Gestionar',
  'page_personalization.capabilities.memory.reference': 'Referenciar memorias guardadas',
  'page_personalization.capabilities.recording.title': 'Modo Grabación',
  'page_personalization.capabilities.recording.desc': 'Accede y revisa transcripciones de tus interacciones.',
  'page_personalization.capabilities.search.title': 'Búsqueda en Internet',
  'page_personalization.capabilities.search.desc': 'Permite al agente buscar en internet para obtener información actualizada.',

  // Connectors Page
  'page_connectors.title': 'Conectores',
  'page_connectors.subtitle': 'Gestiona integraciones con tus herramientas de trabajo.',
  'page_connectors.integrations.title': 'Integraciones Disponibles',
  'page_connectors.tooltip.agent_mode': 'Permite acciones autónomas con confirmación.',
  'page_connectors.status.connected': 'Conectado',
  'page_connectors.status.not_connected': 'No Conectado',
  'page_connectors.button.manage': 'Gestionar',
  'page_connectors.button.connect': 'Conectar',
  
  // Data Controls Page
  'page_datacontrols.title': 'Control de Datos',
  'page_datacontrols.subtitle': 'Gestiona tus datos, privacidad y cómo se usa la información.',
  'page_datacontrols.training.title': 'Entrenamiento y Privacidad',
  'page_datacontrols.training.improve.title': 'Mejorar el modelo',
  'page_datacontrols.training.improve.desc': 'Permite que tus conversaciones anonimizadas se usen para entrenar nuestros modelos.',
  'page_datacontrols.mission.title': 'Datos de Misiones y Conversaciones',
  'page_datacontrols.mission.clear.title': 'Eliminar todos los datos',
  'page_datacontrols.mission.clear.desc': 'Esto eliminará permanentemente todo tu progreso de misiones e historial de conversaciones. Esta acción no se puede deshacer.',
  'page_datacontrols.mission.clear.button': 'Eliminar Datos',
  'page_datacontrols.dialog.clear.title': '¿Estás completamente seguro?',
  'page_datacontrols.dialog.clear.desc': 'Esto eliminará permanentemente todos los datos de misiones y conversaciones. Esta acción no se puede deshacer.',
  'page_datacontrols.dialog.clear.confirm': 'Sí, eliminar datos',

  // Security Page
  'page_security.title': 'Seguridad',
  'page_security.subtitle': 'Gestiona la configuración de seguridad de tu cuenta.',
  'page_security.auth.title': 'Autenticación',
  'page_security.auth.password.title': 'Contraseña',
  'page_security.auth.password.desc': 'Es una buena idea usar una contraseña fuerte que no estés usando en otro lugar.',
  'page_security.auth.password.button': 'Cambiar contraseña',
  'page_security.auth.2fa.title': 'Autenticación de Dos Factores (2FA)',
  'page_security.auth.2fa.desc': 'Añade una capa extra de seguridad a tu cuenta.',
  'page_security.sessions.title': 'Sesiones Activas',
  'page_security.sessions.current.title': 'Sesión Actual',
  'page_security.sessions.current.desc': '{browser} en {os} - {location}',
  'page_security.sessions.current.status': 'Activa ahora',
  'page_security.sessions.logout.button': 'Cerrar sesión en todos los demás dispositivos',
  
  // Agent Brain Specific
  'datacontrols.consents.title': 'Consentimientos de Datos del Agente',
  'datacontrols.consents.description': 'Otorga permisos específicos a los agentes para acceder a tus datos. Esto asegura que tengas un control granular sobre cómo se utiliza tu información. Los cambios se guardan automáticamente.',
  'datacontrols.consents.agent.drwin': 'Dr. Win',
  'datacontrols.consents.agent.validateagent': 'AgenteValidador',
  'datacontrols.consents.agent.createagent': 'AgenteCreador',
  'datacontrols.consents.resource.organization': 'Organización',
  'datacontrols.consents.resource.organization.desc': 'Información legal, tamaño, industria, etc.',
  'datacontrols.consents.resource.projects': 'Proyectos',
  'datacontrols.consents.resource.projects.desc': 'Ideas, borradores y proyectos creados.',
  'datacontrols.consents.action.read': 'Leer',
  'datacontrols.consents.action.search': 'Buscar',
  'datacontrols.consents.action.validate': 'Validar',
  'datacontrols.consents.action.create': 'Crear',
  'org.legal_info': 'Información Legal',
  'org.legal_name': 'Razón Social',
  'org.legal_name.desc': 'El nombre oficial registrado de la empresa.',
  'org.brand_name': 'Nombre Comercial',
  'org.brand_name.desc': 'El nombre utilizado para marketing, si es diferente.',
  'org.vat': 'CIF / NIF',
  'org.vat.desc': 'El número de identificación fiscal único.',
  'org.details': 'Detalles de la Organización',
  'org.country': 'País',
  'org.country.desc': 'El principal país de operación.',
  'org.industry': 'Industria (CNAE)',
  'org.industry.desc': 'El principal sector de actividad económica.',
  'org.size': 'Tamaño de la Empresa',
  'org.size.desc': 'El número de empleados en tu organización.',
  'org.size.solo': 'Autónomo (1)',
  'org.size.micro': 'Micro (1-9)',
  'org.size.sme': 'PYME (10-249)',
  'org.size.mid': 'Mediana (250-1000)',
  'org.size.large': 'Grande (1000+)',
  'org.preferences': 'Preferencias de Ayudas',
  'org.budget': 'Presupuesto Anual I+D',
  'org.budget.desc': 'Presupuesto anual aproximado para proyectos de I+D.',
  'org.languages': 'Idiomas Soportados',
  'org.languages.desc': 'Idiomas para propuestas (separados por comas).',
  'org.update_button': 'Actualizar Perfil',
  
  // Unified Cognitive Profile
  'cognitive_profile.title': 'Perfil Cognitivo Unificado',
  'cognitive_profile.subtitle': 'Este es el núcleo de identidad inteligente de tu organización, la base de conocimiento viva para todos los agentes.',
  'profile.title': 'Perfil Cognitivo',
  'profile.subtitle': 'Esta información servirá como memoria base para todas las operaciones de los agentes.',
  'profile.initial_data': 'Datos Iniciales y Extracción con IA',
  'profile.initial_data.desc': 'Introduce la URL del sitio web para iniciar la extracción automática de información.',
  'profile.company_url': 'URL del Sitio Web',
  'profile.ai_extraction_status': 'IA escaneando sitio web...',
  'profile.ai_suggestion': 'He detectado que tu empresa ofrece soluciones de energía solar en Europa. ¿Deseas que agregue la etiqueta ‘Energías Renovables’ y el público objetivo ‘Empresas industriales’?',
  'profile.basic_info': 'Información Básica',
  'profile.description': 'Descripción de la Empresa',
  'profile.description.desc': 'Un breve resumen de la misión y actividades de tu empresa.',
  'profile.sector': 'Sector Principal',
  'profile.location': 'Ubicación Principal',
  'profile.products': 'Productos / Servicios',
  'profile.products_audience': 'Productos y Público Objetivo',
  'profile.target_audience': 'Público Objetivo',
  'profile.context_docs': 'Documentos de Contexto',
  'profile.context_docs.desc': 'Enriquece el perfil con documentos (PDF, DOCX, etc.). El contenido se extraerá y se pondrá a disposición de los agentes.',
  'profile.upload_button': 'Subir Archivo',
  'profile.doc_table.name': 'Nombre',
  'profile.doc_table.summary': 'Resumen IA',
  'profile.doc_table.tags': 'Etiquetas',
  'profile.update_button': 'Actualizar Perfil',

  // Suite Integrator
  'suite_integrator.title': 'Integrador de la Suite',
  'suite_integrator.subtitle': 'El bus cognitivo que conecta perfiles, agentes y módulos mediante contratos, eventos y memoria semántica.',
  'suite_integrator.contracts.title': 'Contratos de Datos (JSON Schemas)',
  'suite_integrator.contracts.desc': 'Esquemas versionados que garantizan la consistencia de los datos en todo el ecosistema.',
  'suite_integrator.events.title': 'Registro de Eventos en Vivo',
  'suite_integrator.events.desc': 'Flujo en tiempo real de eventos publicados por el integrador para sincronizar los módulos.',
  'suite_integrator.events.table.event': 'Evento',
  'suite_integrator.events.table.source': 'Origen',
  'suite_integrator.events.table.profile': 'ID Perfil',
  'suite_integrator.events.table.correlation': 'ID Correlación',
  'suite_integrator.semantic_search.title': 'Búsqueda Semántica (Memoria Vectorial)',
  'suite_integrator.semantic_search.desc': 'Consulta los perfiles cognitivos usando lenguaje natural.',
  'suite_integrator.semantic_search.placeholder': 'ej: empresas de energía renovable en España con TRL > 5',
  'suite_integrator.semantic_search.button': 'Buscar',
  'suite_integrator.semantic_search.searching': 'Buscando...',
  'suite_integrator.semantic_search.interpretation': 'Interpretación Semántica',
  'suite_integrator.semantic_search.no_results': 'No se encontraron perfiles coincidentes.',

  // Missions Page (Chat)
  'missions.chat.welcome': '¿En qué puedo ayudarte?',
  'missions.chat.placeholder': 'Pregunta lo que quieras',
  'missions.chat.thinking': 'Dr. Win está pensando...',
  'missions.suggestions.title': '¿No sabes por dónde empezar? Prueba una de estas opciones:',
  'missions.suggestions.s1.title': '¿Quieres que analice oportunidades de financiación?',
  'missions.suggestions.s1.desc': 'Puedo revisar las convocatorias activas y decirte cuáles se ajustan mejor a tu empresa o proyecto.',
  'missions.suggestions.s2.title': '¿Quieres que te guíe paso a paso en la aplicación?',
  'missions.suggestions.s2.desc': 'Puedo acompañarte en cada fase: búsqueda, preparación, redacción y envío de la propuesta.',
  'missions.suggestions.s3.title': '¿Quieres que te recuerde los plazos importantes?',
  'missions.suggestions.s3.desc': 'Puedo enviarte alertas antes del cierre de convocatorias o entregas pendientes.',
};

export const translations = {
  en,
  es,
};

export type Language = keyof typeof translations;
export type TranslationKey = keyof typeof en;